# Generated by Django 4.2.3 on 2023-08-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Haqqimizda arxa plan sekil')),
                ('services', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Xidmetler arxa plan sekil')),
                ('blogs', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bloq arxa plan sekil')),
            ],
            options={
                'verbose_name_plural': 'Arxa plan sekilleri',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('footer_text', models.TextField()),
                ('footer_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('apply_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Esas Melumatlar',
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('insta', 'Instagram'), ('fb', 'Facebook'), ('wp', 'Whatsapp')], max_length=100)),
                ('link', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_contact', to='base.main')),
            ],
        ),
    ]
