# Generated by Django 4.2.3 on 2023-08-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_subscribe_remove_openinghours_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
